type IconProps = React.HTMLAttributes<SVGElement>

/* eslint max-lines: off */
export const Icons = {
  spinner: (props?: IconProps) => (
    <svg
      xmlns='http://www.w3.org/2000/svg'
      viewBox='0 0 100 100'
      className='h-60 w-60'
      {...props}
    >
      <g transform='rotate(0 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-1.28s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(32.72727272727273 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-1.15s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(65.45 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-1.02s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(98.18 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-0.89s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(130.90 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-0.76s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(163.63 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-0.64s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(196.36 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-0.51s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(229.09 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-0.38s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(261.81 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-0.25s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(294.54 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='-0.12s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
      <g transform='rotate(327.27 50 50)'>
        <rect
          x='47'
          y='15'
          rx='1.3'
          ry='1.3'
          width='6'
          height='10'
          fill='#09090b'
        >
          <animate
            attributeName='opacity'
            values='1;0'
            keyTimes='0;1'
            dur='1.4s'
            begin='0s'
            repeatCount='indefinite'
          ></animate>
        </rect>
      </g>
    </svg>
  )
}
